### ISSUE TITLE
Launch the interview!

### ISSUE THREAD

**Issue by samglover** [SuffolkLITLab/docassemble-MATCSmallClaims#17]
## To do

**In the GitHub interview repository**
- [ ] Update the repository details:
  - [ ] Update the repository description with the name of the interview.
  - [ ] Update the repository URL with the URL where the live interview can be found.
  - [ ] Add topic tags:
    - [ ] `docassemble-interview`
    - [ ] `live` (if the interview is or is going to be live)
    - [ ] The jurisdiction (i.e., `Massachusetts`)
- [ ] Update the README using the following template:
> This is a Docassemble interview to complete the \[JURISDICTION] \[FORM(S)] forms online. The live interview can be found at \[URL].
- [ ] If there are any outstanding changes to the repository, do a final commit.
- [ ] If the interview is going live, add an interview upkeep workflow (see below).

**On the production server**
- [ ] Install the interview package.
- [ ] Have a pizza party or take a nap or both.

Also, we need a place to store this GitHub action workflow for creating an annual issue to review the repo for updates (errors, changes to the form or law, etc.):

## Interview upkeep workflow

This GitHub action workflow creates an issue every year on August 1st with a brief checklist for maintainers.

File location/name: `.github/workflows/interview-upkeep.yml

```yaml
name: Annual update interview issue
on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: "33 3 1 7 *" # At 3:33am every August 1st

jobs:
  create_issue:
    name: Create update-interview issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create update-interview issue
        run: |
          new_issue_url=$(gh issue create \
            --title "$TITLE" \
            --body "$BODY")
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TITLE: Check this interview for updates
          BODY: |
            - [ ] Check for errors by running through the interview several times. Use different inputs each time.
            - [ ] Check for new versions of the PDF or DOCX forms in the `data/templates` folder.
            - [ ] Check for updates to the law(s) on which the interview is based.
            
            If any of the above reveal a need to update this interview, do the following:
            * Describe the updates necessary in a comment on this issue.
            * Un-assign yourself from this issue
            * Change the project selection for this issue to the Interview Upkeep project.
```
